### ISSUE TITLE
catch-migrate:rollback 多表前缀报错

### ISSUE THREAD

**Issue by tlerbao** [JaguarJack/catch-admin#10]
![image](https://user-images.githubusercontent.com/20442232/88154414-6bae2b00-cc39-11ea-9dae-d23fded16551.png)

如图，因为多了表前缀所以无法rollback，对比所有migrations文件，发现系统原版都$table = $this->table都没有表前缀，而用代码生成器生成的migrations文件是加了表前缀的，可能就是这里导致的多了一份表前缀。

**Comment by JaguarJack** [comment]
个人本地测试没有遇到该情况
