### ISSUE TITLE
批量删除只能删一个的小问题

### ISSUE THREAD

**Issue by tlerbao** [JaguarJack/catch-admin#12]
按照你前端 multiDel 的写法del(this.selectedRowKeys.join(','))结合后端的delete($id)方法只会删除一条记录

因为传过去的是 3,4,5这样的字符串 delete()接收主键数组才行 delete([3,4,5])

小问题，但是不知道是在前端处理好还是后端处理好一点，交给你弄个更优秀的做法把。

**Comment by JaguarJack** [comment]
具体点 接口 方法

**Comment by tlerbao** [comment]
几乎所有的啊，我发现你的前端代码里 基本都有multiDel 这个方法用来批量删除，同样调用的是后端的delete方法。
后端delete方法要么接收数值要么接收数组 ，但现在multiDel传过去的是 3,4,5 字符串
还有批量删除的按钮都加了v-action 可能你在写各个功能列表的时候复制粘贴的，导致这个批量删除的按钮不出现
