### ISSUE TITLE
CatchUpload中的upload方法上传图片之后路径可能有问题

### ISSUE THREAD

**Issue by Alex-Zero** [JaguarJack/catch-admin#16]
可能是由于upload方法中的url参数的设置有问题url = self::getCloudDomain(this−>getDriver()).′/′.this->getLocalPath($path);
![image](https://user-images.githubusercontent.com/6062820/88796185-d7613c80-d1d3-11ea-8fd3-21ddcd341df3.png)
![image](https://user-images.githubusercontent.com/6062820/88796195-db8d5a00-d1d3-11ea-8693-502c193fd817.png)

**Comment by JaguarJack** [comment]
请参考 issue 模版

**Comment by tongxin3267** [comment]
window环境就是有这个问题。我也遇到了

**Comment by JaguarJack** [comment]
并没有什么影响，只是 window 路径问题，不会影响图片访问
