### ISSUE TITLE
图片和文件上传之后无法返回除了url之外的其他数据，比如ID,filename等等

### ISSUE THREAD

**Issue by Alex-Zero** [JaguarJack/catch-admin#17]
如题，只能返回 path或者url
![image](https://user-images.githubusercontent.com/6062820/88796349-0d9ebc00-d1d4-11ea-9707-5e4ed6607538.png)
![image](https://user-images.githubusercontent.com/6062820/88796375-17282400-d1d4-11ea-9bf4-6377b3262487.png)

**Comment by JaguarJack** [comment]
按模版提交 issue
