### ISSUE TITLE
TP框架升级到6.0.3。报错找不到控制器

### ISSUE THREAD

**Issue by tongxin3267** [JaguarJack/catch-admin#18]
# 环境
- 操作系统:win
- php 版本:73
- thinkphp 版本:6.0.3
- Mysql 版本:
- web 服务器:

# 问题
- 问题描述:
升级后报错提示：控制器不存在:app\controller\\catchAdmin\permissions\controller\User
- 问题截图:

# 结果
- 实际结果:
- 预期结果:

# 分析
- 所做的尝试:
    -
    -

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by JaguarJack** [comment]
你需要回退版本，resource 路由在 6.0.3 版本有 bug，没有修复！

**Comment by tongxin3267** [comment]
6.0.2有安全问题。

**Comment by JaguarJack** [comment]
> 6.0.2有安全问题。

在等新版本，我看了记录应该是修复了。等待下吧
