### ISSUE TITLE
CatchAuth.php，传入参数有问题

### ISSUE THREAD

**Issue by LGY-color** [JaguarJack/catch-admin#20]
# 环境
- 操作系统: window10
- php 版本: 7.3
- thinkphp 版本: 6.0.4
- Mysql 版本: 5.7
- web 服务器: wamp

# 问题
- 问题描述:
login中，传入$request->param();如果有额外信息传入，会导致CatchAuth.php，filter函数构造where异常，导致查不到数据直接报错。
- 问题截图:

# 结果
- 实际结果:
- 预期结果:

# 分析
- 所做的尝试:
    -
    -

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by JaguarJack** [comment]
请贴上参数列表，重新开 issue
