### ISSUE TITLE
部门存在三级时，用户管理列表一级部门数据为空的问题

### ISSUE THREAD

**Issue by tlerbao** [JaguarJack/catch-admin#22]
# 环境
- 操作系统:Windows 10
- php 版本:7.3
- thinkphp 版本:6.0.4
- Mysql 版本:5.7
* web 服务器:nginx

# 问题

当部门存在三级部门，而用户又隶属于三级部门，用户管理左侧点击一级部门右侧列表数据不会显示其子部门的用户

# 截图

![image](https://user-images.githubusercontent.com/20442232/97428313-c948c680-1950-11eb-937a-443593f33c39.png)

![11](https://user-images.githubusercontent.com/20442232/97428089-753de200-1950-11eb-8742-e9d74f159032.gif)

# 分析

UserSearch.php中searchDepartmentIdAttr的问题

# 方案:

应该递归查出所有子分类吧

**Comment by tlerbao** [comment]
伤心close，不在提bug和建议了。

**Comment by qingmang** [comment]
哈哈
