### ISSUE TITLE
用户只能隶属最末层部门，这样不合理

### ISSUE THREAD

**Issue by tlerbao** [JaguarJack/catch-admin#23]
# 环境
- 操作系统:Win10
- php 版本:7.3
- thinkphp 版本:6.0.3
- Mysql 版本:5.7
- web 服务器:nginx

# 问题
![image](https://user-images.githubusercontent.com/20442232/97522806-8e3fa500-19db-11eb-876e-abbba7764aa5.png)

如图 给用户指定部门的时候只能隶属于最末层部门，那数据权限里的 部门及部门以下数据似乎就没意义了
比如这个用户应该可以隶属于南京总部的 

# 结果

# 分析

# 方案:

用户应可以隶属于各个层级的部门，这样他的角色数据权限如果是部门及部门一下数据就可以获得到子部门以下的数据了。

**Comment by JaguarJack** [comment]
合理！都是挂在根节点。

**Comment by tlerbao** [comment]
合理个屁啊，我是阿迪达斯得品牌负责人，管理所有门店，你让我归属到根节点，我怎么管理所有门店数据啊，部门及部门以下数据就形同虚设了啊
-总部
  - 阿迪达斯
    * 我是阿迪达斯品牌经理我管理下面全部门店数据
    - 门店A
    - 门店B

**Comment by tlerbao** [comment]
如果隶属于根节点也行，改成一个用户可以隶属于多个部门？
那感觉部门及部门以下数据还是形同虚设啊。

老吴啊 小宝贝啊 认真对待一下 我这个超级粉丝提得issues吧
