### ISSUE TITLE
当前访问路由未定义或不匹配

### ISSUE THREAD

**Issue by zhouyouth** [JaguarJack/catch-admin#30]
# 环境
- 操作系统:
- php 版本:
- thinkphp 版本:
- Mysql 版本:
- web 服务器:

# 问题
- 问题描述:
  访问路由经常出现
Argument 3 passed to think\Log::log() must be of the type array, string given, called in
- 问题截图:

# 结果
- 实际结果:
- 预期结果:

# 分析
- 所做的尝试:
    -
    

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by JaguarJack** [comment]
访问什么样的路由产生的

**Comment by zhouyouth** [comment]
上面是拦截了系统的异常造成的,和系统没有关系,现在的问题是

# 环境
- 操作系统:
- php 版本: 
- thinkphp 版本:
- Mysql 版本:
- web 服务器:

# 问题 
- 问题描述: 生成代码路由没法访问

- 问题截图:
  当前访问路由未定义或不匹配
 

# 结果
- 实际结果:
  当前访问路由未定义或不匹配
- 预期结果:
  访问正常
# 分析
- 所做的尝试:
    - 分析源码，发现解析module.json异常， module.json 是生成模块命令生成的，
    发现module.json 生成时 有[{KEYWORDS}]，造成解析不正常  完整的
      {
      "name": "helloworld",
      "alias": "helloworld",
      "description": "helloworld",
      "version": "1.0.0",
      "keywords": [{KEYWORDS}],
      "order": 0,
      "services": [
      "\\catchAdmin\\helloworld\\HelloworldService"
      ],
      "aliases": {},
      "files": [],
      "requires": [],
      "enable": true
      }

# 方案:
 git clone 新的版本，发现生成模块 不在有[{KEYWORDS}]，是不是新的版本修复了，老的版本该怎么升级

**Comment by zhouyouth** [comment]
源码确实,改过了, 老的项目还用的老的版本
![Uploading image.png…]()

**Comment by zhouyouth** [comment]
![image](https://user-images.githubusercontent.com/17350538/114502957-24e8e100-9c5f-11eb-8402-2c237f35f220.png)
新版本确实修复了

**Comment by JaguarJack** [comment]
直接 pull 就好了。模块使用后台代码生产的，有个创建模块按钮，命令行之后要删除了。windows cms 无法识别中文串，没做适配

**Comment by zhouyouth** [comment]
ok
