### ISSUE TITLE
V1界面空白

### ISSUE THREAD

**Issue by dengsuchuan** [JaguarJack/catch-admin#39]
# 环境
- 操作系统: WINDOWS10
- php 版本:PHP7.4
- thinkphp 版本:6.0.2
- Mysql 版本:8.5
- web 服务器:yarn serve

# 问题
- 问题描述:
1. 使用git方式拉下后端v1分支，conmposer后报错【There are no commands defined in the "jwt" namespace.】百度谷歌后无法解决。
2. git方式无法成功安装，采用【composer create-project jaguarjack/catchadmin:dev-master catchAdmin】的方式直接安装后端项目并初始化数据库。
3. 前后端无任何报错并成功登录，但仅能显示【主页】内容，请求只进行了【info】和【roles】的请求，其他页面均为空白，查看前端无报错，点击其他菜单也没有任何请求

- 问题截图:
![image](https://user-images.githubusercontent.com/19817415/201887021-d2d72679-b241-4742-8f84-e21bc73ce56d.png)
![image](https://user-images.githubusercontent.com/19817415/201887349-e8f892d3-4127-432e-a3c4-bdb2f0205812.png)
![image](https://user-images.githubusercontent.com/19817415/201887692-f71cf47e-7fd8-428f-8779-41229ec3a041.png)
![image](https://user-images.githubusercontent.com/19817415/201887733-0861b2e9-6dae-43fe-b684-607996ca4132.png)

# 结果
- 实际结果:
显示相应菜单中的页面
- 预期结果:
页面空白

# 分析
- 所做的尝试:
    - 修改后端路由代码
    - 

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by JaguarJack** [comment]
可能需要你自己 debug 下，时间太久了
