### ISSUE TITLE
[dev] composer install 报错：require(../../catch/src/Support/helpers.php): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by jiangslee** [JaguarJack/catch-admin#40]
https://github.com/JaguarJack/catch-admin/blob/a5eeceec175e858799151b4216250020f4215cf1/.gitignore#L8

https://github.com/JaguarJack/catch-admin/blob/a5eeceec175e858799151b4216250020f4215cf1/composer.json#L25-L28

**Comment by JaguarJack** [comment]
先等等，还没开发完。

**Comment by jiangslee** [comment]
> 先等等，还没开发完。

期待，还以为可以先睹为快

**Comment by JaguarJack** [comment]
> > 先等等，还没开发完。
> 
> 期待，还以为可以先睹为快

年前争取发个 demo 出来
