### ISSUE TITLE
数据库数据不存在

### ISSUE THREAD

**Issue by taoyao-code** [JaguarJack/catch-admin#41]
# 环境
- 操作系统: mac
- php 版本: 8.1
- thinkphp 版本: laraver版本
- Mysql 版本: 5.7
- web 服务器:

# 问题
- 问题描述:
安装后，数据库数据没有。
- 问题截图:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/38855041/215303112-8adf6367-907f-479d-b775-a2985006d38b.png">
<img width="775" alt="image" src="https://user-images.githubusercontent.com/38855041/215303125-384266cd-8094-4b04-86db-74f7ffa5d8e1.png">

# 结果
- 实际结果:
- 预期结果:

# 分析
- 所做的尝试:
    -
    -

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by JaguarJack** [comment]
权限模块默认不启用。登陆功能是否可以？

**Comment by taoyao-code** [comment]
> 权限模块默认不启用。登陆功能是否可以？

直接没有生成数据，数据库，表数据是空的

**Comment by JaguarJack** [comment]
> > 权限模块默认不启用。登陆功能是否可以？
> 
> 
> 
> 直接没有生成数据，数据库，表数据是空的

的确。用户的初始化数据没导入进去
