### ISSUE TITLE
什么时候能支持sail开发环境

### ISSUE THREAD

**Issue by wcz0** [JaguarJack/catch-admin#43]
# 环境
- 操作系统: docker linux
- php 版本: 8.2
- Laravel 版本: 10
- Mysql 版本: 8.0
- web 服务器: null

# 问题
- 问题描述:
使用sail开发, 这是mysql版本太高的原因吗
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-api-php default charset utf8mb4 collate utf8mb4_general_ci' at line 1 (Connection: , SQL: create database if not exists grizzly-api-php default charset utf8mb4 collate utf8mb4_general_ci)
```
- 问题截图:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/22549312/219762487-fef5f051-0c80-4912-ba0f-80d869f3fb87.png">

# 结果
- 实际结果:
- 预期结果:

# 分析
- 所做的尝试:
    -
    -

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by JaguarJack** [comment]
不支持 `grizzly-api-php` 这种命名格式，你可以改成 `grizzly_api_php`

**Comment by wcz0** [comment]
原来如此
