### ISSUE TITLE
官网文档编辑有问题

### ISSUE THREAD

**Issue by endLife888** [JaguarJack/catch-admin#44]
![image](https://user-images.githubusercontent.com/42015805/219989024-175a12f9-de61-4458-b712-1299f13b1bc6.png)
该上述命令应该是php artisan catch:module:install <module>
而且官网的githup链接也需要更换下，404了

**Comment by JaguarJack** [comment]
哪个页面的 github 链接，发下看看

**Comment by JaguarJack** [comment]
> ![image](https://user-images.githubusercontent.com/42015805/219989024-175a12f9-de61-4458-b712-1299f13b1bc6.png) 该上述命令应该是php artisan catch:module:install 而且官网的githup链接也需要更换下，404了

已修复
