### ISSUE TITLE
前后分离

### ISSUE THREAD

**Issue by oppsDayly** [JaguarJack/catch-admin#49]
大佬啊，能不能把前端和后端分开来啊，看起来太蹩脚了。

**Comment by JaguarJack** [comment]
目前只能自己手动分离！

**Comment by heyailab** [comment]
现在看到的目录结构和文档的
├─resources
│  ├─admin (前端目录)

不一样了？
安装方式也变了？

**Comment by JaguarJack** [comment]
> 现在看到的目录结构和文档的 ├─resources │ ├─admin (前端目录)
> 
> 不一样了？ 安装方式也变了？

tp 的话切到 tp 分支就可以了。master 分支是 Laravel 版本的
