### ISSUE TITLE
RequestHandledListener的问题

### ISSUE THREAD

**Issue by oppsDayly** [JaguarJack/catch-admin#51]
我看项目对返回数据进行format了，但是为什么我在App\http\controller 里面的返回也会被格式化，我想要自定义code码，
在枚举后我该怎么实现呢？

**Comment by JaguarJack** [comment]
目前成功的 code 码是 10000，固定的。非 10000 的，可以通过异常的 code 自定义。

目前劫持了 RequestHandledListener 的会影响所有接口。等下个版本核心，只会劫持 catchadmin 的后台接口。
