### ISSUE TITLE
创建模块之后查询不到路由

### ISSUE THREAD

**Issue by SuiranQaQ** [JaguarJack/catch-admin#54]
# 环境
- 操作系统:centos7.6
- php 版本:7.2.33
- thinkphp 版本
- Mysql 版本:5.6.50
- web 服务器

# 问题
- 问题描述:
使用create创建模块和后台管理一键生成了，但是查询不到路由，后端部署在服务器，前端本地运行，后台管理可以看到这个模块，但是路由查询不到
- 问题截图:
![5AQ5X7N`)S{3 Z2JQL5Z%X6](https://user-images.githubusercontent.com/97267668/233265827-8fe3c1de-2fb0-4982-86ce-efb2bddb6f46.png)
![@QI0MU2T9AWH(A0Y69Q415S](https://user-images.githubusercontent.com/97267668/233265844-5e609419-a0f1-4ef1-92a9-63c46a647f34.png)
![image](https://user-images.githubusercontent.com/97267668/233266038-e1327c25-6eb0-4a5a-b829-a1e02fcb5f6a.png)

# 结果
- 实际结果:
- 并没有包含
- 预期结果:
php think:route:list应该包含新创建的模块路由
# 分析
- 所做的尝试:
    -权限777
    -删除重新创建模块和后台生成

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by SuiranQaQ** [comment]
![image](https://user-images.githubusercontent.com/97267668/233266498-74219a3c-e80c-425f-a399-27a83bc78745.png)

**Comment by JaguarJack** [comment]
> ![image](https://user-images.githubusercontent.com/97267668/233266498-74219a3c-e80c-425f-a399-27a83bc78745.png)

- 检查 runtime\catch 目录下是否有缓存
- 检查对应的模块是否开启, module.json 文件 enable 字段

**Comment by SuiranQaQ** [comment]
好的，我去试试看
