### ISSUE TITLE
关于使用使用后的感受

### ISSUE THREAD

**Issue by oppsDayly** [JaguarJack/catch-admin#55]
总体来说是非常好，非常方便的，但是使用的时候有几点问题吧在这里询问一下开发者
1.既然已经采用前后端分离了为什么还直接使用laravel提供的vue开发环境为什么不使用vue cli，这样项目完整整洁，便于开发。
（如果开发者需要，我可以帮助分离）
2.为什么不采用安装包的形式直接composer install 而是采用这种一体框架的形式。
3.缺少api文档开发过程不太流畅。

**Comment by JaguarJack** [comment]
1. 分离难度其实不大。我自己尝试过分离，大概花了不到一小时，就完全出来了。
`为什么要嵌套在 Laravel` 中呢？是模块化的原因，开发之初是想通过模块化这种方式，通过社区来提供各种那样的功能，方便大家使用。可以从 cms 模块看出来。如果使用前后端分离，可能步骤就会麻烦很多

2. 我是想把他作为 project 来做，因为里面很多业务功能。主要的核心放在了 `catchadmin/core` 里
3.  开发文档一直打算做的，但不知道以什么形式共享出去
