### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by 4GUO** [JaguarJack/catch-admin#56]
# 环境
- 操作系统:mac
- php 版本:8.1.13
- Laravel 版本:10.0
- Mysql 版本:
- web 服务器:

# 问题
- 问题描述:
- composer install 不成功

- 问题截图:
- 
<img width="1524" alt="image" src="https://user-images.githubusercontent.com/65385011/235309627-a38e0fb3-94e5-4a53-b1a8-8e761c27b412.png">

# 结果
- 实际结果:
- 预期结果:

# 分析
- 所做的尝试:
    - 更新了本地的composer到最新版本，尝试了官方的composer源和aliyun的源，均不行
    -

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by 4GUO** [comment]
装了8.2 
重装icu72
重装了composer
composer clearcache
compose selfupdate
composer config -g repo.packagist composer https://repo.packagist.org
最后成功了

因为我发现实际上packagist.org是有3.3.2版本的
最后尝试恢复了一下官方源，因为一开始我想着重装了composer 应该源就是官方源了。

**Comment by JaguarJack** [comment]
> 装了8.2 重装icu72 重装了composer composer clearcache compose selfupdate composer config -g repo.packagist composer https://repo.packagist.org 最后成功了
> 
> 因为我发现实际上packagist.org是有3.3.2版本的 最后尝试恢复了一下官方源，因为一开始我想着重装了composer 应该源就是官方源了。

https://catchadmin.com/docs/3.0/faq 常见问题里有写
