### ISSUE TITLE
生产环境部署catch-admin

### ISSUE THREAD

**Issue by lindeliang** [JaguarJack/catch-admin#58]
1、在生产环境中怎么部署呀，启动vue报错
![微信图片_20230607141121](https://github.com/JaguarJack/catch-admin/assets/33930859/2bcec08c-beb8-45f4-a677-92e148b21e74)

**Comment by JaguarJack** [comment]
路径问题? npm run build？
我一直用的 yarn, yarn build 即可。
你这个启动的不是 dev 环境么

**Comment by lindeliang** [comment]
大佬有没有部署文档呀

**Comment by JaguarJack** [comment]
> 

https://catchadmin.com/docs/3.0/catchadmin/install#%E9%A1%B9%E7%9B%AE%E9%83%A8%E7%BD%B2%E9%85%8D%E7%BD%AE
