### ISSUE TITLE
权限菜单的2个问题

### ISSUE THREAD

**Issue by ThreadDeath** [JaguarJack/catch-admin#59]
大佬，有2个问题看是不是问题

![image](https://github.com/JaguarJack/catch-admin/assets/5794404/dc2f6830-7add-4192-9d43-f5f6b71a63df)

1.排序无效

2.无法自定义权限标识比如article_create，要在数据库里改

**Comment by JaguarJack** [comment]
> 大佬，有2个问题看是不是问题
> 
> ![image](https://user-images.githubusercontent.com/5794404/269134176-dc2f6830-7add-4192-9d43-f5f6b71a63df.png)
> 
> 1.排序无效
> 
> 2.无法自定义权限标识比如article_create，要在数据库里改

第一个似乎没做排序，只是有排序字段，我来加下。
第二个的确没办法，是写死在代码里的标志，只能是 `article@create`，其中 article 是 controller，create 是 controller 的方法
