### ISSUE TITLE
V2版本 角色不能正常的添加和保存了  V2版本php端 在安装过程中不能正常安装数据表

### ISSUE THREAD

**Issue by 567ai** [JaguarJack/catch-admin#60]
bug  新装 catchadmin V2版本的时候  php think catch：install 安装数据库 不完整 

报错  Declaration of DepartmentsSeed::run() must be compatible with Phinx\Seed\AbstractSeed::run(): void

处理  所有实现Phinx\Seed\AbstractSeed::run() 都需要 ：void  其中还有一个方法 做了return

<img width="279" alt="0ce0064315824e9679fb599bd4af714b_720" src="https://github.com/JaguarJack/catch-admin/assets/56379165/75c90822-e816-477d-8717-2e0bf7699d43">

 今天刚发现的就是  角色不能新增和更新了  突然不可以了  我刚下载git 版本 搭建好发现也不行
<img width="492" alt="109edb5487bcc79a4c0d9f6b77912850" src="https://github.com/JaguarJack/catch-admin/assets/56379165/55f38fa5-02c2-4cd4-af29-d03a4f6b49a9">
<img width="487" alt="4bfc8f07ca62c667838219cf570f56ec" src="https://github.com/JaguarJack/catch-admin/assets/56379165/b611c2d0-db34-4464-aafc-76b6f970178e">

改为 this.formCreate.fApi.el('_permissions')  可以正常使用

但是原因没找到 不知道是不是包的问题

**Comment by JaguarJack** [comment]
一般都是 form create 的问题
