### ISSUE TITLE
登陆没有返回权限信息 白屏

### ISSUE THREAD

**Issue by JueMeiAlg** [JaguarJack/catch-admin#61]
# 环境
- 操作系统:
- php 版本:
- Laravel 版本:
- Mysql 版本:
- web 服务器:

# 问题
- 问题描述:
安装完成以后访问, 页面都是空白 发现获取用户信息没有返回 相应的权限信息导致的, 现在这个怎么调整呢, 我现在吧以前的 数据库备份过来 覆盖进去 登陆也会是这样, 发现版本代码是一致的 现在不知道哪里的问题了
- 问题截图:
![image](https://github.com/JaguarJack/catch-admin/assets/34858740/78f0bc07-40c6-4f0c-b46f-2820c3c92ec2)
![image](https://github.com/JaguarJack/catch-admin/assets/34858740/00e68a39-b58f-4044-bf22-5715e0316a26)

# 结果
- 实际结果:
- 预期结果:

# 分析
- 所做的尝试:
    -
    -

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by JaguarJack** [comment]
看看权限模块有没有启用，这里面没有关联关系。极大可能是模块权限没有开启导致的

**Comment by JueMeiAlg** [comment]
能不能透露下在哪里打开这个 权限模块呢

**Comment by JaguarJack** [comment]
> 能不能透露下在哪里打开这个 权限模块呢

![image](https://github.com/JaguarJack/catch-admin/assets/16589247/96c4c67b-e8a2-451a-931d-df05f97bba03)

```json
[
    {
        "title": "权限管理",
        "name": "permissions",
        "path": "permissions",
        "keywords": "权限, 角色, 部门",
        "description": "权限管理模块",
        "provider": "\\Modules\\Permissions\\Providers\\PermissionsServiceProvider",
        "version": "1.0.0",
        "enable": true // 模块开启字段
    }
]
```

**Comment by JueMeiAlg** [comment]
嗯 解决问题了 这个文件一般怎么产生的 我看我新迁移的项目下面没有这个文件 还是在老的项目里面 拷贝了一份出来 解决的

**Comment by JaguarJack** [comment]
> 嗯 解决问题了 这个文件一般怎么产生的 我看我新迁移的项目下面没有这个文件 还是在老的项目里面 拷贝了一份出来 解决的

安装模块产生的。系统默认模块不产生该文件。默认模块在配置文件 catch.php 中有配置

**Comment by JaguarJack** [comment]
> 嗯 解决问题了 这个文件一般怎么产生的 我看我新迁移的项目下面没有这个文件 还是在老的项目里面 拷贝了一份出来 解决的

我看了下，这可能是由于我没有将 permissions 设置成默认模块的原因，等会给 core 发个版修复下
