### ISSUE TITLE
Laravel 版本Schemas新增表不添加软删除会报错

### ISSUE THREAD

**Issue by ouyuan2016** [JaguarJack/catch-admin#62]
# 环境
- 操作系统:
- php 版本:8.2
- Laravel 版本:10
- Mysql 版本:8
- web 服务器:nginx

# 问题
- 问题描述:
Schemas新增表的时候不添加软删除,访问接口的时候会报错属性冲突的错误
Modules\Shops\Models\XXXXXX and Catch\Traits\DB\BaseOperate define the same property ($fields) in the composition of Modules\Shops\Models\XXXXXX. However, the definition differs and is considered incompatible. Class was composed

- 问题截图:
![image](https://github.com/JaguarJack/catch-admin/assets/20590949/fd2f1c39-db5a-459e-aa50-d766918e46a0)

# 结果
- 预期结果:
正确生成model文件

# 分析

# 方案:
- 解决方案:
目前删除$fields $form这两个属性就可以了，希望后面能自动生成正常的model文件

> 请在问题解决后关闭 issue

**Comment by JaguarJack** [comment]
好的，这两天修复！

**Comment by JaguarJack** [comment]
已经修复，顺便核心升级至 Laravel11。
