### ISSUE TITLE
自动生成的create.vue模板样式不正确

### ISSUE THREAD

**Issue by ouyuan2016** [JaguarJack/catch-admin#63]
# 问题
- 问题描述:
生成的样式问题，标题和内容的间隔不够

- 问题截图:
![image](https://github.com/JaguarJack/catch-admin/assets/20590949/0475261d-2997-497e-bb5e-e02c7ace8c2a)

# 结果
- 实际结果:
- 预期结果:
    -调整标题和内容正常

**Comment by JaguarJack** [comment]
只能自己在模板自己调整
