### ISSUE TITLE
[建议]BaseOperate文件 提供模型关联with的函数或者参数

### ISSUE THREAD

**Issue by ouyuan2016** [JaguarJack/catch-admin#65]
目前我只能重写BaseOperate里面getList的方法加入参数$with=>getList($with=[]) 然后代码加入->with($with) 

希望添加一个[模型关联](https://learnku.com/docs/laravel/10.x/eloquent-relationships/14889)的函数或者可选参选查询关联的模型信息

**Comment by JaguarJack** [comment]
getList 方法允许注入一个回调钩子
```php
$this->model->setBeforeGetList(function($query){
    return $query->with() // 记得一定要 Return
})->getList()
```
可以使用这个钩子在进行其他一些查询

**Comment by ouyuan2016** [comment]
ok
