### ISSUE TITLE
如何调整默认的菜单列表

### ISSUE THREAD

**Issue by JueMeiAlg** [JaguarJack/catch-admin#67]
![image](https://github.com/JaguarJack/catch-admin/assets/34858740/ee4048a1-e1f5-4a65-98c0-c8b9da874d16)

我现在需要把 账号管理移动到别的 菜单项里面 ,个人中心要隐藏起来 ,整个用户管理的 根菜单也要隐藏移除了,  但是这个 用户管理 不在权限管理 ->菜单管理 里面 操作移除, 现在 怎么把他搞掉呢

**Comment by JaguarJack** [comment]
用户管理是使用的静态路由，也就是 vue 路由写死的，可以在下面的文件找到
```shell
modules/User/views/router.ts
```
如果需要动态，可以按照相关路由规则添加即可

**Comment by JueMeiAlg** [comment]
好 成功转移
