### ISSUE TITLE
文档挂了？

### ISSUE THREAD

**Issue by cevin** [JaguarJack/catch-admin#68]
<img width="483" alt="image" src="https://github.com/JaguarJack/catch-admin/assets/338110/5da592d9-6b6a-48e0-9962-2917f3912875">

**Comment by JaguarJack** [comment]
![image](https://github.com/JaguarJack/catch-admin/assets/16589247/e78ffb2b-95b7-48e9-8447-aa5a01b53137)
正常访问的

**Comment by cevin** [comment]
https://github.com/JaguarJack/catch-admin/assets/338110/5fbc35cd-3b9d-458e-b376-629e5ed4d5fa

**Comment by cevin** [comment]
确实打不开

**Comment by JaguarJack** [comment]
![image](https://github.com/JaguarJack/catch-admin/assets/16589247/db89ccbf-d41f-4390-ae2c-1e82d7fc2634)
右击有个 clear 吧 storage_session 清空看看呢

**Comment by cevin** [comment]
> ![image](https://private-user-images.githubusercontent.com/16589247/326703015-db89ccbf-d41f-4390-ae2c-1e82d7fc2634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjE3NTUsIm5iZiI6MTcxNDQ2MTQ1NSwicGF0aCI6Ii8xNjU4OTI0Ny8zMjY3MDMwMTUtZGI4OWNjYmYtZDQxZi00MzkwLWFlMmMtMWU4MmQ3ZmMyNjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA3MTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YjFkYjBiYmYzNGZjNmI3ZTllOGQyYjg4NDgxNGNhZjEwNWU3NDg5NGZlNWUwNDQ1ZjViYmJiNjI3YTMwNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZOe8uZyRrZZrPkQozIwTy1cTID7pLtlDzyEgFOPj7vs) 右击有个 clear 吧 storage_session 清空看看呢

https://gitee.com/api/v5/user/starred/JaguarJack/catchadmin?access_token=*******

清空也不行。star这个接口的项目不存在

**Comment by JaguarJack** [comment]
> > ![image](https://private-user-images.githubusercontent.com/16589247/326703015-db89ccbf-d41f-4390-ae2c-1e82d7fc2634.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NjE3NTUsIm5iZiI6MTcxNDQ2MTQ1NSwicGF0aCI6Ii8xNjU4OTI0Ny8zMjY3MDMwMTUtZGI4OWNjYmYtZDQxZi00MzkwLWFlMmMtMWU4MmQ3ZmMyNjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDA3MTczNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YjFkYjBiYmYzNGZjNmI3ZTllOGQyYjg4NDgxNGNhZjEwNWU3NDg5NGZlNWUwNDQ1ZjViYmJiNjI3YTMwNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZOe8uZyRrZZrPkQozIwTy1cTID7pLtlDzyEgFOPj7vs) 右击有个 clear 吧 storage_session 清空看看呢
> 
> https://gitee.com/api/v5/user/starred/JaguarJack/catchadmin?access_token=*******
> 
> 清空也不行。star这个接口的项目不存在

你重新 clear 下，然后强制清理缓存下，应该就可以了。
接口变成这个了 https://gitee.com/api/v5/user/starred/catchadmin/catchAdmin?access_token=
