### ISSUE TITLE
关于laravel文档地址

### ISSUE THREAD

**Issue by ajiho** [JaguarJack/catch-admin#73]
非catch-admin相关的问题，所以建议模板就不用了

我在B站评论区后盾人大叔那个他发的他要翻译laravel文档视频看到你发的地址：
https://laravel-docs.catchadmin.com/

![image](https://github.com/user-attachments/assets/88bd5942-0c57-4367-9c40-c1ab79f1ba75)

也在https://learnku.com社区看到过你发的有关于使用vitepress翻译的文章

我观察了一下，这个翻译文档，有些地方，你好像改了一些，比如
![image](https://github.com/user-attachments/assets/1f9314cf-4b8d-43a8-8d14-7a44a153c428)
![image](https://github.com/user-attachments/assets/fa5ab669-d863-444d-b5cf-a281f206c3d5)

以及我把laravel官方的文档弄到viteperss中，laravel的文档它有些代码片段是这种格式，比如：
```
If you need to report different types of exceptions in different ways, you may use the `reportable` method to register a closure that should be executed when an exception of a given type needs to be reported. Laravel will determine what type of exception the closure reports by examining the type-hint of the closure:

    use App\Exceptions\InvalidOrderException;

    /**
     * Register the exception handling callbacks for the application.
     */
    public function register(): void
    {
        $this->reportable(function (InvalidOrderException $e) {
            // ...
        });
    }

When you register a custom exception reporting callback using the `reportable` method, Laravel will still log the exception using the default l
```
它并没有添加代码块的符号,在viteperss中它就没有高亮，这部分它是你都处理好了，请问你这部分都是手动一个一个处理的吗？通过编辑器批量替换？还是有什么特殊的方法处理的呢？

还有你翻译是用的什么翻译方法呢？

因为我也想自己弄一个laravel的文档，特地来请教，你是如何解决这些个问题的。

**Comment by JaguarJack** [comment]
1. 代码块大部分都是通过提示词让 AI 处理的。部分手动处理

2. 翻译之前是使用 codz，因为 codz 的 chatGPT4 是免费的。Laravel 有些单文档非常巨大，所以我都是手动去处理。大概处理了两周左右的时间。在处理之后我会稍微修正下

3. 的确被我删除了。有右侧的导航即可，个人认为比文档内的方便。

**Comment by ajiho** [comment]
多谢解答，可想而知，工作量还是很大的，不过好在文档不频繁更新，再加上vitepress用户体验比较好，辛苦一次还是值得的。

**Comment by JaguarJack** [comment]
> 多谢解答，可想而知，工作量还是很大的，不过好在文档不频繁更新，再加上vitepress用户体验比较好，辛苦一次还是值得的。

laravel 文档也是在不断更新的。这也是一个工作量

**Comment by ajiho** [comment]
> > 多谢解答，可想而知，工作量还是很大的，不过好在文档不频繁更新，再加上vitepress用户体验比较好，辛苦一次还是值得的。
> 
> laravel 文档也是在不断更新的。这也是一个工作量

如果是纯英文的好解决，可以想办法自动化一下，比较好解决，问题是中文文档想和英文文档同步就不好弄了，
比如有一天，laravel在其中一个md文件增加了一段内容，又或者助手函数文件`helpers.md`增加了几个方法，如果没人提醒或者自己观察到，就没有办法同步了，不知道有什么优雅的方法可以知道它具体那个地方改了，然后通知你，具体的位置然后增加。

learnku社区是基本上玩laravel的热爱laravel的聚集在一起了，会经常更新和维护吧。

这种个人托管，如果又不想开源的，真的不好弄。如果有什么好的思路可以大家一起交流，谢谢

**Comment by ajiho** [comment]
还有，我做了一个测试，我把laravel文档4.2到11.x所有的markdown丢vitepress里，viteperss开始有瓶颈了，启动开发服务器还是build都要很久的时间。

**Comment by JaguarJack** [comment]
> 还有，我做了一个测试，我把laravel文档4.2到11.x所有的markdown丢vitepress里，viteperss开始有瓶颈了，启动开发服务器还是build都要很久的时间。

对的。这是一直存在的问题

**Comment by JaguarJack** [comment]
> > > 多谢解答，可想而知，工作量还是很大的，不过好在文档不频繁更新，再加上vitepress用户体验比较好，辛苦一次还是值得的。
> 
> > 
> 
> > laravel 文档也是在不断更新的。这也是一个工作量
> 
> 
> 
> 如果是纯英文的好解决，可以想办法自动化一下，比较好解决，问题是中文文档想和英文文档同步就不好弄了，
> 
> 比如有一天，laravel在其中一个md文件增加了一段内容，又或者助手函数文件`helpers.md`增加了几个方法，如果没人提醒或者自己观察到，就没有办法同步了，不知道有什么优雅的方法可以知道它具体那个地方改了，然后通知你，具体的位置然后增加。
> 
> 
> 
> learnku社区是基本上玩laravel的热爱laravel的聚集在一起了，会经常更新和维护吧。
> 
> 
> 
> 这种个人托管，如果又不想开源的，真的不好弄。如果有什么好的思路可以大家一起交流，谢谢

人工校验。每天看一下就行了😂或者写个脚本监控 laravel doc 的 commit
