### ISSUE TITLE
新建菜单之后，菜单变成了一级的目录

### ISSUE THREAD

**Issue by 404LT** [JaguarJack/catch-admin#76]
# 环境
- 操作系统:mac
- php 版本:8.2
- Laravel 版本:
- Mysql 版本:
- web 服务器:

# 问题
- 问题描述:
- 作者你好，请问为什么我按照B站的介绍视频，在新建模块后操作新建目录和新建菜单之后，菜单变成了一级的目录，以下是我的数据和界面截图

- 问题截图:
- 
<img width="1498" alt="image" src="https://github.com/user-attachments/assets/1723025a-8ceb-46cd-ba33-a3e481b17b35" />

<img width="1285" alt="image" src="https://github.com/user-attachments/assets/fdf5957d-c9e6-4330-b03a-0623cc2da937" />
<img width="1209" alt="image" src="https://github.com/user-attachments/assets/5f49e149-03ee-4f52-9565-50f4b89d149a" />

# 结果
- 实际结果:
- 预期结果:

# 分析
- 所做的尝试:
    -
    -

# 方案:
- 解决方案:

> 请在问题解决后关闭 issue

**Comment by 404LT** [comment]
<img width="1512" alt="image" src="https://github.com/user-attachments/assets/c23e5982-0ce1-483d-bf64-bb596fdb1d48" />

**Comment by JaguarJack** [comment]
策略是这样的，你再添加一个就会显示多级了

**Comment by 404LT** [comment]
> 策略是这样的，你再添加一个就会显示多级了

感谢解答
