### ISSUE TITLE
微信模块图文上传封面BUG

### ISSUE THREAD

**Issue by tlerbao** [JaguarJack/catch-admin#9]
1、attachments表url字段长度太小，导致报错。
2、返回给前端的图片URL不对，导致图片无法显示。

**Comment by tlerbao** [comment]
补充说明：

第一 
attachments表url字段默认长度verchar 100，导致event('attachment'）事件直接报 SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 错误；如下图。
![9](https://user-images.githubusercontent.com/20442232/88067211-48d03800-cba1-11ea-9b14-ab245629ae9e.gif)

第二
将attachments表url字段长度改为255可修复上面的错误，但微信图文管理上传封面回调返回的图片路径不对，
![10](https://user-images.githubusercontent.com/20442232/88067929-25f25380-cba2-11ea-8e44-571637a82277.gif)
![1](https://user-images.githubusercontent.com/20442232/88067946-2a1e7100-cba2-11ea-8709-413e5c456083.png)

这种路径
/F:\WorkSpace\Test.Project\CatchAdmin\CatchAdmin\public/images\20200721\5bf818494128385fb87bb2417dab24a3.png

**Comment by Alex-Zero** [comment]
复议

**Comment by JaguarJack** [comment]
URL 你再看看，我本地测试是正常的 URL 返回的

**Comment by tlerbao** [comment]
> URL 你再看看，我本地测试是正常的 URL 返回的

你一定不是windows环境，看我另一个pr

配置文件中的app()->getRootPath()会让getCloudDomain方法返回带有F:/xxx/xxx这样的路径最后形成 http://xxx.com/F:/xx/xxx/upload.jpg 这样的完整路径，去掉配置文件app()->getRootPath()似乎就行了。
